AWSTemplateFormatVersion: "2010-09-09"
Description: Stack to create Api gateway
Parameters:
  Namespace:
    Type: String
    Description: Namespace for resources
  Bucket:
    Type: String
    Description: Containing source files
  BuildStamp:
    Type: String
    Description: String to be used to create artifacts
Resources:

  MongoUriParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Namespace}/mongo-uri"
      Type: String
      Value: "test-value"
