AWSTemplateFormatVersion: "2010-09-09"
Description: Stack to create Api gateway
Parameters:
  Namespace:
    Type: String
    Description: Namespace for resources
  Bucket:
    Type: String
    Description: Containing source files
  BuildStamp:
    Type: String
    Description: String to be used to create artifacts
Resources:

  MongoUriParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Namespace}/mongo-uri"
      Type: String
      Value: "test-value"

  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.9
      Content:
        S3Bucket: !Ref Bucket
        S3Key: !Sub "build/${Namespace}-${BuildStamp}-layer.zip"
      LayerName: !Sub "${Namespace}-Layer"
      LicenseInfo: MIT