---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Stack for creating client EC2 Machine"
 
Parameters:
 Namespace:
   Type: String
 Bucket:
   Type: String
 TaxiLocationTopicArn:
   Type: String

Resources:
  DriverEc2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Namespace}-driver-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: 'BuildFileAccess'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:Get*'
                  - 's3:List*'
                Resource: !Sub 'arn:aws:s3:::${Bucket}/build/${Namespace}/*'
        - PolicyName: 'PublishToSns'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'sns:Publish'
                  - 'sns:Subscribe'
                  - 'sns:Unsubscribe'
                  - 'sns:ConfirmSubscription'
                Resource: !Ref TaxiLocationTopicArn
      Tags:
        - Key: Name
          Value: !Sub '${Namespace}-driver-role'
        - Key: Namespace
          Value: !Sub '${Namespace}'

  DriveEc2InstanceProfile:
   Type: AWS::IAM::InstanceProfile
   Properties:
     Roles:
       - !Ref DriverEc2Role
     InstanceProfileName: !Sub '${Namespace}-driver-profile'

  DriverEc2Instance:
   Type: AWS::EC2::Instance
   Properties:
     IamInstanceProfile: !Ref DriveEc2InstanceProfile
     ImageId: 'ami-0022f774911c1d690'
     InstanceType: t2.micro
     Tags:
       - Key: Name
         Value: !Sub '${Namespace}-driver'
       - Key: Namespace
         Value: !Sub '${Namespace}'

