AWSTemplateFormatVersion: "2010-09-09"
Description: Stack to create all lambda functions

Parameters:
  Namespace:
    Type: String
    Description: Namespace for resources
  Bucket:
    Type: String
    Description: Containing source files
  BuildStamp:
      Type: String
      Description: String to be used to create artifacts
  DbSubnetId:
    Type: String
  LambdaSecurityGroup:
    Type: String
  MongoUriSsmParameterName:
    Type: String
  MqttPrivateIp:
    Type: String
  MqttPublicIp:
    Type: String

Resources:

  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleArchitectures:
        - 'x86_64'
      CompatibleRuntimes:
        - python3.7
        - python3.8
      Content:
        S3Bucket: !Ref Bucket
        S3Key: !Sub "build/${Namespace}-${BuildStamp}-layer.zip"
      LayerName: !Sub "${Namespace}-${BuildStamp}-Layer"
      LicenseInfo: MIT

  RegisterLambda:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: !Sub "${Namespace}-Register-Function"
        Runtime: python3.7
        Handler: 'register.handler'
        MemorySize: 128
        Timeout: 10
        Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${Namespace}-Register-Lambda-Role"
        Layers:
          - !Ref LambdaLayer
        Code:
          S3Bucket: !Ref Bucket
          S3Key: !Sub "build/${Namespace}/${BuildStamp}/lambda.zip"
        VpcConfig:
          SecurityGroupIds:
            - !Ref LambdaSecurityGroup
          SubnetIds:
            - !Ref DbSubnetId
        Environment:
          Variables:
            NAMESPACE: !Ref Namespace

  LoginLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Namespace}-Login-Function"
      Runtime: python3.7
      Handler: 'login.handler'
      MemorySize: 128
      Timeout: 10
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${Namespace}-Login-Lambda-Role"
      Code:
        S3Bucket: !Ref Bucket
        S3Key: !Sub "build/${Namespace}/${BuildStamp}/lambda.zip"
      Layers:
        - !Ref LambdaLayer
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref DbSubnetId
      Environment:
        Variables:
          NAMESPACE: !Ref Namespace
          SSM_MONGO_URI: !Ref MongoUriSsmParameterName
          MQTT_PUBLIC_IP: !Ref MqttPublicIp
          MQTT_PRIVATE_IP: !Ref MqttPrivateIp
          TOPIC_ARN_PREFIX: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${Namespace}-taxi'

  LogoffLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Namespace}-Logoff-Function"
      Runtime: python3.7
      Handler: 'logoff.handler'
      MemorySize: 128
      Timeout: 10
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${Namespace}-Logoff-Lambda-Role"
      Code:
        S3Bucket: !Ref Bucket
        S3Key: !Sub "build/${Namespace}/${BuildStamp}/lambda.zip"
      Environment:
        Variables:
          NAMESPACE: !Ref Namespace

  FindTaxiLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Namespace}-FindTaxi-Function"
      Runtime: python3.7
      Handler: 'find_taxi.handler'
      MemorySize: 128
      Timeout: 10
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${Namespace}-FindTaxi-Lambda-Role"
      Code:
        S3Bucket: !Ref Bucket
        S3Key: !Sub "build/${Namespace}/${BuildStamp}/lambda.zip"
      Environment:
        Variables:
          NAMESPACE: !Ref Namespace

  CleanupLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Namespace}-Cleanup-Function"
      Runtime: python3.7
      Handler: 'cleanup.handler'
      MemorySize: 128
      Timeout: 10
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${Namespace}-Cleanup-Lambda-Role"
      Code:
        S3Bucket: !Ref Bucket
        S3Key: !Sub "build/${Namespace}/${BuildStamp}/lambda.zip"
      Environment:
        Variables:
          NAMESPACE: !Ref Namespace

  LocationLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Namespace}-Location-Function"
      Runtime: python3.7
      Handler: 'location.handler'
      MemorySize: 128
      Timeout: 10
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${Namespace}-Location-Lambda-Role"
      Code:
        S3Bucket: !Ref Bucket
        S3Key: !Sub "build/${Namespace}/${BuildStamp}/lambda.zip"
      Environment:
        Variables:
          NAMESPACE: !Ref Namespace

Outputs:

  LoginLambdaArn:
    Value: !GetAtt LoginLambda.Arn
  LogoffLambdaArn:
    Value: !GetAtt LogoffLambda.Arn
  RegisterLambdaArn:
    Value: !GetAtt RegisterLambda.Arn
  FindTaxiLambdaArn:
    Value: !GetAtt FindTaxiLambda.Arn
  CleanupLambdaArn:
    Value: !GetAtt CleanupLambda.Arn
  LocationLambdaArn:
    Value: !GetAtt LocationLambda.Arn

