AWSTemplateFormatVersion: "2010-09-09"
Description: Stack to create all lambda functions

Parameters:
  Namespace:
    Type: String
    Description: Namespace for resources
  Bucket:
    Type: String
    Description: Containing source files
  BuildStamp:
      Type: String
      Description: String to be used to create artifacts
  DbSubnetId:
    Type: String
  LambdaSecurityGroup:
    Type: String

Resources:
  RegisterLambda:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: !Sub "${Namespace}-Register-Function"
        Runtime: python3.9
        Handler: 'register.handler'
        MemorySize: 128
        Timeout: 10
        Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${Namespace}-Register-Lambda-Role"
        Layers:
          - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:${Namespace}-Layer:1"
        Code:
          S3Bucket: !Ref Bucket
          S3Key: !Sub "build/${Namespace}/${BuildStamp}/lambda.zip"
        VpcConfig:
          SecurityGroupIds:
            - !Ref LambdaSecurityGroup
          SubnetIds:
            - !Ref DbSubnetId

  LoginLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Namespace}-Login-Function"
      Runtime: python3.9
      Handler: 'login.handler'
      MemorySize: 128
      Timeout: 10
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${Namespace}-Login-Lambda-Role"
      Code:
        S3Bucket: !Ref Bucket
        S3Key: !Sub "build/${Namespace}/${BuildStamp}/lambda.zip"

  LogoffLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Namespace}-Logoff-Function"
      Runtime: python3.9
      Handler: 'logoff.handler'
      MemorySize: 128
      Timeout: 10
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${Namespace}-Logoff-Lambda-Role"
      Code:
        S3Bucket: !Ref Bucket
        S3Key: !Sub "build/${Namespace}/${BuildStamp}/lambda.zip"

  FindTaxiLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Namespace}-FindTaxi-Function"
      Runtime: python3.9
      Handler: 'find_taxi.handler'
      MemorySize: 128
      Timeout: 10
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${Namespace}-FindTaxi-Lambda-Role"
      Code:
        S3Bucket: !Ref Bucket
        S3Key: !Sub "build/${Namespace}/${BuildStamp}/lambda.zip"

  CleanupLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Namespace}-Cleanup-Function"
      Runtime: python3.9
      Handler: 'cleanup.handler'
      MemorySize: 128
      Timeout: 10
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${Namespace}-Cleanup-Lambda-Role"
      Code:
        S3Bucket: !Ref Bucket
        S3Key: !Sub "build/${Namespace}/${BuildStamp}/lambda.zip"

  LocationLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Namespace}-Location-Function"
      Runtime: python3.9
      Handler: 'location.handler'
      MemorySize: 128
      Timeout: 10
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${Namespace}-Location-Lambda-Role"
      Code:
        S3Bucket: !Ref Bucket
        S3Key: !Sub "build/${Namespace}/${BuildStamp}/lambda.zip"

Outputs:

  LoginLambdaArn:
    Value: !GetAtt LoginLambda.Arn
  LogoffLambdaArn:
    Value: !GetAtt LogoffLambda.Arn
  RegisterLambdaArn:
    Value: !GetAtt RegisterLambda.Arn
  FindTaxiLambdaArn:
    Value: !GetAtt FindTaxiLambda.Arn
  CleanupLambdaArn:
    Value: !GetAtt CleanupLambda.Arn
  LocationLambdaArn:
    Value: !GetAtt LocationLambda.Arn

