AWSTemplateFormatVersion: "2010-09-09"
Description: Master stack which creates all required nested stacks

Parameters:
  Namespace:
    Type: String
    Description: Namespace for resources
  Bucket:
    Type: String
    Description: S3Bucket Name to use for files
  BuildStamp:
    Type: String
    Description: String to be used to create artifacts
  DbSubnetId:
    Type: String
  LambdaSecurityGroup:
    Type: String

Resources:

  SecurityStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub 'https://${Bucket}.s3.amazonaws.com/build/${Namespace}/${BuildStamp}/stack/security.yml'
      Parameters:
        Namespace: !Ref Namespace

  LambdaStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn:
      - SecurityStack
    Properties:
      TemplateURL: !Sub 'https://${Bucket}.s3.amazonaws.com/build/${Namespace}/${BuildStamp}/stack/lambda.yml'
      Parameters:
        Namespace: !Ref Namespace
        Bucket: !Ref Bucket
        BuildStamp: !Ref BuildStamp
        DbSubnetId: !Ref DbSubnetId
        LambdaSecurityGroup: !Ref LambdaSecurityGroup

  ApiStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub 'https://${Bucket}.s3.amazonaws.com/build/${Namespace}/${BuildStamp}/stack/api.yml'
      Parameters:
        Namespace: !Ref Namespace
        LoginLambdaArn: !GetAtt LambdaStack.Outputs.LoginLambdaArn
        LogoffLambdaArn: !GetAtt LambdaStack.Outputs.LogoffLambdaArn
        RegisterLambdaArn: !GetAtt LambdaStack.Outputs.RegisterLambdaArn
        FindTaxiLambdaArn: !GetAtt LambdaStack.Outputs.FindTaxiLambdaArn
        CleanupLambdaArn: !GetAtt LambdaStack.Outputs.CleanupLambdaArn
        ApiGatewayStageName: 'v1'

  SnsStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub 'https://${Bucket}.s3.amazonaws.com/build/${Namespace}/${BuildStamp}/stack/sns.yml'
      Parameters:
        Namespace: !Ref Namespace
        LocationLambdaArn: !GetAtt LambdaStack.Outputs.LocationLambdaArn

  DriverStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub 'https://${Bucket}.s3.amazonaws.com/build/${Namespace}/${BuildStamp}/stack/driver.yml'
      Parameters:
        Namespace: !Ref Namespace
        Bucket: !Ref Bucket
        TaxiLocationTopicArn: !GetAtt SnsStack.Outputs.TaxiLocationTopicArn
