AWSTemplateFormatVersion: "2010-09-09"
Description: Master stack which creates all required nested stacks

Parameters:
  Namespace:
    Type: String
    Description: Namespace for resources
  Bucket:
    Type: String
    Description: S3Bucket Name to use for files
  BuildStamp:
    Type: String
    Description: String to be used to create artifacts
  SubnetId:
    Type: String
  SecurityGroup:
    Type: String
  MongoUriSsmParameterName:
    Type: String
    Default: "/mongo-uri"
  MqttSsmPublicIp:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/mqtt-host-public"
  MqttSsmPrivateIp:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/mqtt-host-private"

Resources:

  SecurityStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub 'https://${Bucket}.s3.amazonaws.com/build/${Namespace}/${BuildStamp}/stack/security.yml'
      Parameters:
        Namespace: !Ref Namespace

  LambdaStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub 'https://${Bucket}.s3.amazonaws.com/build/${Namespace}/${BuildStamp}/stack/lambda.yml'
      Parameters:
        Namespace: !Ref Namespace
        Bucket: !Ref Bucket
        BuildStamp: !Ref BuildStamp
        SubnetId: !Ref SubnetId
        SecurityGroup: !Ref SecurityGroup
        MongoUriSsmParameterName: !Ref MongoUriSsmParameterName
        MqttPublicIp: !Ref MqttSsmPublicIp
        MqttPrivateIp: !Ref MqttSsmPrivateIp
        CommonLambdaRoleArn: !GetAtt SecurityStack.Outputs.CommonLambdaRoleArn

  ApiStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub 'https://${Bucket}.s3.amazonaws.com/build/${Namespace}/${BuildStamp}/stack/api.yml'
      Parameters:
        Namespace: !Ref Namespace
        LoginLambdaArn: !GetAtt LambdaStack.Outputs.LoginLambdaArn
        LogoffLambdaArn: !GetAtt LambdaStack.Outputs.LogoffLambdaArn
        RegisterLambdaArn: !GetAtt LambdaStack.Outputs.RegisterLambdaArn
        LocationLambdaArn: !GetAtt LambdaStack.Outputs.LocationLambdaArn
        FindTaxiLambdaArn: !GetAtt LambdaStack.Outputs.FindTaxiLambdaArn
        AcceptRideLambdaArn: !GetAtt LambdaStack.Outputs.AcceptRideLambdaArn
        RideUpdateLambdaArn: !GetAtt LambdaStack.Outputs.RideUpdateLambdaArn
        CleanupLambdaArn: !GetAtt LambdaStack.Outputs.CleanupLambdaArn
        ApiGatewayStageName: 'v1'

  SnsStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub 'https://${Bucket}.s3.amazonaws.com/build/${Namespace}/${BuildStamp}/stack/sns.yml'
      Parameters:
        Namespace: !Ref Namespace
        LocationLambdaArn: !GetAtt LambdaStack.Outputs.LocationLambdaArn
