AWSTemplateFormatVersion: "2010-09-09"
Description: "Stack for SNS Topic"


Parameters:
  Namespace:
    Type: String
    Description: Namespace for resources
  LocationLambdaArn:
    Type: String

Resources:

  LocationUpdateTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref LocationLambdaArn
          Protocol: lambda
      Tags:
        - Key: Namespace
          Value: !Sub "${Namespace}"
      TopicName: !Sub "${Namespace}-taxi-location"

  LocationLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LocationLambdaArn
      Principal: sns.amazonaws.com
      SourceArn: !Ref LocationUpdateTopic

Outputs:
  TaxiLocationTopicArn:
    Value: !Ref LocationUpdateTopic